from . import education_course
from . import education_course_change
from . import product
from . import res_partner
from . import sale_order
from . import sale_order_line
from . import sale_order_line_payer
from . import sale_order_template
from . import sale_order_template_line
from . import sale_order_template_option
