from . import education_course
from . import education_course_change
from . import product
from . import product_pricelist
from . import product_pricelist_type
from . import res_partner
from . import res_partner_enrollment
from . import sale_order
from . import sale_order_line
from . import sale_order_line_payer
from . import sale_order_template
from . import sale_order_template_line
from . import sale_order_template_option
